# Generated by Django 5.2.1 on 2025-06-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
