# Generated by Django 5.2.1 on 2025-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default='No Snippet', max_length=255, verbose_name='Article snippet'),
        ),
    ]
