# Generated by Django 5.2.1 on 2025-08-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_header_img_alter_article_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='header_img',
            new_name='header_image',
        ),
    ]
